# Generated by Django 5.1.3 on 2025-01-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('empresa', models.CharField(max_length=100)),
                ('idguia', models.IntegerField()),
                ('srcfecha', models.DateTimeField()),
                ('stsguia', models.IntegerField(default=1)),
                ('srcnombres', models.CharField(max_length=30)),
                ('srcapelluno', models.CharField(max_length=20)),
                ('srcapelldos', models.CharField(max_length=20)),
                ('srctelefono', models.IntegerField()),
                ('srcdireccion', models.CharField(max_length=100)),
                ('dstnombres', models.CharField(max_length=30)),
                ('dstapelluno', models.CharField(max_length=20)),
                ('dstapelldos', models.CharField(max_length=20)),
                ('dsttelefono', models.IntegerField()),
                ('dstdireccion', models.CharField(max_length=100)),
                ('peso', models.IntegerField()),
                ('stspago', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('regsts', models.IntegerField(default=1)),
                ('fecha_reg', models.DateTimeField(auto_now_add=True)),
                ('fecha_mod', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
