# Generated by Django 5.1.3 on 2025-01-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkgbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
